### ISSUE TITLE
人不多，聊个无关的话题

### ISSUE THREAD

**Issue by lenmao** [Memoyu/mbill_wechat_app#2]
看着那最早的一估的感触，我直接大半夜笑出来声了~~~~~~~

**Comment by Memoyu** [comment]
😁身为一枚纯后端，做这玩意就纯属图一乐，平时记录一下成长也挺好

**Comment by Memoyu** [comment]
@lenmao 
😁身为一枚纯后端，做这玩意就纯属图一乐，平时记录一下成长也挺好
