### ISSUE TITLE
搞笑～

### ISSUE THREAD

**Issue by caishengmao** [Memoyu/mbill_wechat_app#3]
echart 功能在哪  功能实现了吗

**Comment by Memoyu** [comment]
> echart 功能在哪 功能实现了吗
有实现，在WithEcharts分支中，实际没对接业务，只是展示了图表，以及假数据展示，后来因为感觉占用包太大了，换了ucharts，目前新版本的就用的是ucharts

**Comment by Memoyu** [comment]
@caishengmao 
有实现的，具体实现在WithEcharts分支下，后来感觉我在这用echarts有点大材小用了而且包挺大的，后来就转用ucharts了，目前新版本就使用ucharts做的；
README下的timeline也有相关的文章说明使用，需要的可以看看
