### ISSUE TITLE
演示系统一直报错

### ISSUE THREAD

**Issue by Blackcells** [Memoyu/mbill_wechat_app#4]
如何加上作者
有没有部署文档
是否支持共享账本

**Comment by Memoyu** [comment]
@Blackcells 
刚刚尝试了一下，并没有报错呀，正常使用呢
1、你可以邮箱联系我哟，mmy6076@outlook.com;
2、目前并没有部署文档，需要帮助的你可以直接联系我；
3、目前是没有共享账本相关功能的，不过可以交流交流，开发不是啥问题；
