### ISSUE TITLE
老大有时间可以整一个部署文档嘛

### ISSUE THREAD

**Issue by dudt** [Memoyu/mbill_wechat_app#7]

**Comment by Memoyu** [comment]
可以，我最近也整理了脚本，好像基本都差不多了，不过部署还是很简单的

**Comment by Memoyu** [comment]
@Mabisi 
可以将就的看看这个：[mbill部署相关 ](https://www.yuque.com/memoyu/sz8ae0/pnbr6haohkhid0tf)
有什么不清楚的，可以随时联系我

**Comment by dudt** [comment]
> @Mabisi 可以将就的看看这个：[mbill部署相关 ](https://www.yuque.com/memoyu/sz8ae0/pnbr6haohkhid0tf) 有什么不清楚的，可以随时联系我

太好了，感谢老大

**Comment by Memoyu** [comment]
> > @Mabisi 可以将就的看看这个：[mbill部署相关 ](https://www.yuque.com/memoyu/sz8ae0/pnbr6haohkhid0tf) 有什么不清楚的，可以随时联系我
> 
> 太好了，感谢老大

不客气🤓
